### ISSUE TITLE
Feat: GameModel 점수 측정 기능 구현

### ISSUE THREAD

**Issue by sjsjsj1246** [SWE-team11/tetris#14]
## 작업사항
보드의 상태에 따라 점수가 측정됩니다. 따라서 점수 데이터를 게임모델에 추가하고

ConfigModel의 게임 난이도에 따라 블럭이 생성되는 확률과 그에 따른 첨수 측정을 해야 합니다.

Timer가 지날 때 마다 점수 추가
MoveDown할 때 추가 점수
즉시 하강 시 거리만큼 추가 점수
게임 스피드 비율에 따라 추가 점수
한 줄이 지워질 때 마다 점수 추가

**Comment by sjsjsj1246** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #14: Feat: BoardModel에 난이도, 아이템 모드 반영, 점수 측정 추가](https://trello.com/c/TfPDCHoA/36-issue-14-feat-boardmodel%EC%97%90-%EB%82%9C%EC%9D%B4%EB%8F%84-%EC%95%84%EC%9D%B4%ED%85%9C-%EB%AA%A8%EB%93%9C-%EB%B0%98%EC%98%81-%EC%A0%90%EC%88%98-%EC%B8%A1%EC%A0%95-%EC%B6%94%EA%B0%80)

**Comment by Istiopaxx** [comment]
https://github.com/SWE-team11/tetris/pull/52#issuecomment-1103874390
