### ISSUE TITLE
docs: 이슈, PR템플릿, git hook 작성

### ISSUE THREAD

**Issue by Istiopaxx** [SWE-team11/tetris#18]
## 개발사항

이슈와 PR 템플릿, git hook(필요하다면)을 작성합니다.

**Comment by sjsjsj1246** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #18: docs: 이슈, PR템플릿, git hook 작성](https://trello.com/c/bAbXJnjk/40-issue-18-docs-%EC%9D%B4%EC%8A%88-pr%ED%85%9C%ED%94%8C%EB%A6%BF-git-hook-%EC%9E%91%EC%84%B1)
