### ISSUE TITLE
Refactor: 블럭 움직이기 기능

### ISSUE THREAD

**Issue by Istiopaxx** [SWE-team11/tetris#28]
### 문제사항

1. #3 에서 기존 블럭을 움직이는 방식인 프로젝션을 재활용하기 힘듭니다. 
2. `Down`, `Right`, `Left`의 `canMove` 메서드가 중복이 있습니다.

### 리팩토링 방안

1. `move` 기능을 다음과 같은 로직으로 재구성합니다.
    + 먼저 `eraseCurr` 호출
    + `move` 호출(어떤 클래스인지 따라 다름)
    + `placeBlock` 호출
    + `placeBlock`은 가능하다면 성공, 자리에 이미 블럭이 있다면 실패를 반환
    + 실패 시 `fallback` 호출(클래스마다 구현이 다름)

### 테스트 항목

---

## 추가사항

추가적으로 알아야하는 사항을 작성해주세요.

**Comment by sjsjsj1246** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #28: Refactor: 블럭 움직이기 기능](https://trello.com/c/Me6Ap50y/55-issue-28-refactor-%EB%B8%94%EB%9F%AD-%EC%9B%80%EC%A7%81%EC%9D%B4%EA%B8%B0-%EA%B8%B0%EB%8A%A5)
