### ISSUE TITLE
Feat: gradle 및 JUnit/stylecheck 설정

### ISSUE THREAD

**Issue by Istiopaxx** [SWE-team11/tetris#32]
## 개발사항

gradle 빌드 도구 설정 및 JUnit과 stylecheck, 빌드 커맨드를 설정합니다.

---

## 추가사항

추가적으로 알아야하는 사항을 작성해주세요.

**Comment by sjsjsj1246** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #32: Feat: gradle 및 JUnit/stylecheck 설정](https://trello.com/c/kYyTFPOR/61-issue-32-feat-gradle-%EB%B0%8F-junit-stylecheck-%EC%84%A4%EC%A0%95)
