### ISSUE TITLE
Feat: JUnit 프레임워크 적용

### ISSUE THREAD

**Issue by Istiopaxx** [SWE-team11/tetris#36]
## 개발사항

Junit 프레임워크를 적용합니다.
Junit 5가 최신 버전이므로 아마도 5버전을 사용할 것으로 예상합니다.

---

## 추가사항

기존 코드의 테스트 코드 작성은 따로 이슈 생성하도록 하겠습니다.
이 이슈에 대해 PR이 merge되면 앞으로 작성하는 코드는 테스트를 작성하여 주세요.

**Comment by sjsjsj1246** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #36: Feat: JUnit 프레임워크 적용](https://trello.com/c/9zqRXE10/67-issue-36-feat-junit-%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%AC-%EC%A0%81%EC%9A%A9)
