### ISSUE TITLE
Feat: 게임 일시정지 창 뷰 구현

### ISSUE THREAD

**Issue by Istiopaxx** [SWE-team11/tetris#85]
## 개발사항

게임 일시정지 창 뷰를 제대로 구현합니다.

---

## 추가사항

추가적으로 알아야하는 사항을 작성해주세요.

**Comment by sjsjsj1246** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #85: Feat: 게임 일시정지 창 뷰 구현](https://trello.com/c/TTCz4i5E/137-issue-85-feat-%EA%B2%8C%EC%9E%84-%EC%9D%BC%EC%8B%9C%EC%A0%95%EC%A7%80-%EC%B0%BD-%EB%B7%B0-%EA%B5%AC%ED%98%84)
